# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/git/digital-circuits-desighs-workspace/Vivado/projectSemester/projectSemester.srcs/sources_1/ip/Int_PLL/Int_PLL.xci
# IP: The module: 'Int_PLL' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/git/digital-circuits-desighs-workspace/Vivado/projectSemester/projectSemester.gen/sources_1/ip/Int_PLL/Int_PLL_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Int_PLL'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/git/digital-circuits-desighs-workspace/Vivado/projectSemester/projectSemester.gen/sources_1/ip/Int_PLL/Int_PLL.xdc
# XDC: The top module name and the constraint reference have the same name: 'Int_PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/git/digital-circuits-desighs-workspace/Vivado/projectSemester/projectSemester.gen/sources_1/ip/Int_PLL/Int_PLL_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Int_PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/git/digital-circuits-desighs-workspace/Vivado/projectSemester/projectSemester.srcs/sources_1/ip/Int_PLL/Int_PLL.xci
# IP: The module: 'Int_PLL' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/git/digital-circuits-desighs-workspace/Vivado/projectSemester/projectSemester.gen/sources_1/ip/Int_PLL/Int_PLL_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Int_PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/git/digital-circuits-desighs-workspace/Vivado/projectSemester/projectSemester.gen/sources_1/ip/Int_PLL/Int_PLL.xdc
# XDC: The top module name and the constraint reference have the same name: 'Int_PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/git/digital-circuits-desighs-workspace/Vivado/projectSemester/projectSemester.gen/sources_1/ip/Int_PLL/Int_PLL_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Int_PLL'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
