#!/usr/bin/env python3
"""Emit Q15 lookup tables consumed by the spectrumAnalyzer program.

Run from the program root:
    python3 scripts/gen_tables.py
Outputs:
    src/twiddle_lut.c   - FFT twiddle factors W^k = e^{-j 2 pi k / N}, k in 0..N/2-1
    src/window_lut.c    - Hann window: 0.5 * (1 - cos(2 pi n / N)), n in 0..N-1
"""

import math
import sys
from pathlib import Path

N_FFT  = 1024
N_BARS = 32
F_BIN_MIN = 4    # ~63 Hz at 16 kHz / 1024
F_BIN_MAX = 510  # ~7.97 kHz


def q15(x: float) -> int:
    """Saturating round to int16."""
    v = int(round(x * 32767.0))
    return max(-32768, min(32767, v))


def emit_array_c(path: Path, name: str, values: list[int], doc: str) -> None:
    out = []
    out.append('// Auto-generated by scripts/gen_tables.py - do not edit.')
    out.append(f'// {doc}')
    out.append('#include <stdint.h>')
    out.append('')
    out.append(f'const int16_t {name}[{len(values)}] = {{')
    per_line = 8
    for i in range(0, len(values), per_line):
        chunk = values[i : i + per_line]
        line = ', '.join(f'{v:6d}' for v in chunk)
        comma = ',' if i + per_line < len(values) else ''
        out.append(f'    {line}{comma}')
    out.append('};')
    path.write_text('\n'.join(out) + '\n', encoding='utf-8')
    print(f'wrote {path}')


def main() -> int:
    here = Path(__file__).resolve().parent.parent
    src = here / 'src'
    src.mkdir(exist_ok=True)

    # Twiddle: real interleaved imag, length 2 * N/2 = N int16, with W^k = (cos, -sin)
    twiddle: list[int] = []
    for k in range(N_FFT // 2):
        theta = -2.0 * math.pi * k / N_FFT
        twiddle.append(q15(math.cos(theta)))
        twiddle.append(q15(math.sin(theta)))
    emit_array_c(
        src / 'twiddle_lut.c',
        'twiddle_lut',
        twiddle,
        f'Twiddle factors for {N_FFT}-pt FFT, Q15, interleaved [re0, im0, re1, im1, ...]',
    )

    # Hann window
    hann = [q15(0.5 * (1.0 - math.cos(2.0 * math.pi * n / N_FFT))) for n in range(N_FFT)]
    emit_array_c(
        src / 'window_lut.c',
        'hann_lut',
        hann,
        f'Hann window, {N_FFT} samples, Q15',
    )

    # Log-spaced bar bin boundaries — bar i covers FFT bins [b[i], b[i+1])
    ratio = (F_BIN_MAX / F_BIN_MIN) ** (1.0 / N_BARS)
    boundaries: list[int] = []
    for i in range(N_BARS + 1):
        b = int(round(F_BIN_MIN * (ratio ** i)))
        if boundaries and b <= boundaries[-1]:
            b = boundaries[-1] + 1     # enforce monotonic, no empty bar
        boundaries.append(min(b, F_BIN_MAX + 1))
    emit_array_uint16_c(
        src / 'bars_lut.c',
        'bar_bin_boundary',
        boundaries,
        f'{N_BARS} log-spaced bin boundaries from bin {F_BIN_MIN} to {F_BIN_MAX}',
    )

    return 0


def emit_array_uint16_c(path: Path, name: str, values: list[int], doc: str) -> None:
    out = []
    out.append('// Auto-generated by scripts/gen_tables.py - do not edit.')
    out.append(f'// {doc}')
    out.append('#include <stdint.h>')
    out.append('')
    out.append(f'const uint16_t {name}[{len(values)}] = {{')
    per_line = 8
    for i in range(0, len(values), per_line):
        chunk = values[i : i + per_line]
        line = ', '.join(f'{v:4d}' for v in chunk)
        comma = ',' if i + per_line < len(values) else ''
        out.append(f'    {line}{comma}')
    out.append('};')
    path.write_text('\n'.join(out) + '\n', encoding='utf-8')
    print(f'wrote {path}')


if __name__ == '__main__':
    sys.exit(main())
