// Auto-generated by scripts/gen_tables.py
#include <stdint.h>

const uint16_t bar_bin_boundary[33] = {
       4,    5,    6,    7,    8,    9,   10,   12,
      13,   16,   18,   21,   25,   29,   33,   39,
      45,   53,   61,   71,   83,   96,  112,  130,
     152,  177,  205,  239,  278,  324,  377,  438,
     510
};
